spring:
  application:
    name: admin
  main:
    allow-circular-references: true
  rabbitmq:
    listener:
      simple:
        acknowledge-mode: manual
        default-requeue-rejected: false

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    database: MYSQL
    generate-ddl: false
    show-sql: false
    hibernate:
      ddl-auto: none
      hibernate.connection.CharSet: utf8
      hibernate.connection.characterEncoding: utf8
      hibernate.connection.useUnicode: true
      globally_quoted_identifiers: true
    properties:
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
      hibernate.show_sql: false
      hibernate.format_sql: false
      hibernate.jdbc.batch_size: 500
      hibernate.order_inserts: true
      hibernate.order_updates: true
  datasource:
    databaseDriverName: com.mysql.cj.jdbc.Driver
    url: 'jdbc:mysql://localhost:3306/nepalfresh?serverTimezone=Asia/Kathmandu&zeroDateTimeBehavior=convertToNull'
    username: root
    password: root
    maxPool: 5
    maxIdle: 4
    minIdle: 0
  liquibase:
    enabled: true
    #    drop-first: false
    change-log: classpath:admin.changelog/changelog-master.yml
#    default-schema: public
server:
  port: 8081

jwt:
  key: ${SECRET_KEY}

#mail:
#  username: ${MAIL_USERNAME}
#  password: ${MAIL_PASSWORD}
#  host: ${MAIL_HOST}
#  port: ${MAIL_PORT}

#origin: ${BASE_URL}

